import {
  User,
  Course,
  ScheduleItem,
  AttendanceRecord,
  StaffAttendanceRecord,
  GradeRecord,
  Announcement,
  Branch,
  Room,
  SchoolCalendarConfig,
  AdmissionApplication,
  TeacherTopicPlan,
  LeaveApplication,
  AssessmentItem,
} from './types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'br-1',
    code: 'MAIN-01',
    name: 'Main Metropolitan Campus',
    address: '100 University Avenue, Academic District',
    phone: '+1 (555) 019-2831',
    principalName: 'Dr. Arthur Vance',
  },
  {
    id: 'br-2',
    code: 'NORTH-02',
    name: 'North Innovation Wing',
    address: '450 Technology Parkway, North Campus',
    phone: '+1 (555) 019-2832',
    principalName: 'Dr. Sarah Jenkins',
  },
];

export const INITIAL_ROOMS: Room[] = [
  { id: 'rm-101', branchId: 'br-1', roomNumber: '204', name: 'Physics Lab A', capacity: 35, type: 'lab' },
  { id: 'rm-102', branchId: 'br-1', roomNumber: '108', name: 'Chemistry Hall', capacity: 40, type: 'classroom' },
  { id: 'rm-103', branchId: 'br-1', roomNumber: '312', name: 'Humanities Room 312', capacity: 30, type: 'classroom' },
  { id: 'rm-201', branchId: 'br-2', roomNumber: 'Lab B', name: 'Innovation & AI Lab', capacity: 32, type: 'lab' },
  { id: 'rm-202', branchId: 'br-2', roomNumber: '310', name: 'Literature Lecture Room', capacity: 30, type: 'classroom' },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'Dr. Sarah Jenkins',
    email: 's.jenkins@edupulse.edu',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    department: 'IT & System Administration',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    pin: '1234',
    baseSalary: 6500,
    phone: '+1 (555) 111-2222',
  },
  {
    id: 'principal-1',
    name: 'Dr. Arthur Vance',
    email: 'a.vance@edupulse.edu',
    role: 'principal',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
    department: 'Executive Office',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    pin: '2222',
    baseSalary: 7500,
    phone: '+1 (555) 222-3333',
  },
  {
    id: 'teacher-1',
    name: 'Prof. Elena Rostova',
    email: 'e.rostova@edupulse.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    department: 'Science & Mathematics',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    pin: '1111',
    baseSalary: 5200,
    subjects: ['AP Physics C', 'Calculus BC'],
    phone: '+1 (555) 333-4444',
  },
  {
    id: 'teacher-2',
    name: 'Dr. Robert Sterling',
    email: 'r.sterling@edupulse.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    department: 'Natural Sciences',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    pin: '3333',
    baseSalary: 5000,
    subjects: ['Honors Chemistry', 'Advanced Biology'],
    phone: '+1 (555) 444-5555',
  },
  {
    id: 'teacher-3',
    name: 'Ms. Maya Lin',
    email: 'm.lin@edupulse.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    department: 'Humanities & History',
    branchId: 'br-2',
    branchName: 'North Innovation Wing',
    pin: '4444',
    baseSalary: 4800,
    subjects: ['World History', 'American Literature'],
    phone: '+1 (555) 555-6666',
  },
  {
    id: 'teacher-4',
    name: 'Mr. David Hayes',
    email: 'd.hayes@edupulse.edu',
    role: 'teacher',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    department: 'Computer Science',
    branchId: 'br-2',
    branchName: 'North Innovation Wing',
    pin: '5555',
    baseSalary: 5400,
    subjects: ['Computer Science Principles', 'Robotics & AI'],
    phone: '+1 (555) 666-7777',
  },
  {
    id: 'staff-1',
    name: 'Rachel Adams',
    email: 'r.adams@edupulse.edu',
    role: 'staff',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=200',
    department: 'Academic Registrar & Admissions',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    pin: '7777',
    baseSalary: 3800,
    phone: '+1 (555) 777-8888',
  },
  {
    id: 'student-1',
    name: 'Marcus Vance',
    email: 'm.vance@student.edupulse.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    gradeLevel: 'Grade 11',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    studentIdNumber: 'STU-2025-0101',
    parentContact: '+1 (555) 234-5678',
  },
  {
    id: 'student-2',
    name: 'Sophia Rodriguez',
    email: 's.rodriguez@student.edupulse.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    gradeLevel: 'Grade 11',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    studentIdNumber: 'STU-2025-0102',
    parentContact: '+1 (555) 345-6789',
  },
  {
    id: 'student-3',
    name: 'Ethan Thorne',
    email: 'e.thorne@student.edupulse.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    gradeLevel: 'Grade 11',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    studentIdNumber: 'STU-2025-0103',
    parentContact: '+1 (555) 456-7890',
  },
  {
    id: 'student-4',
    name: 'Chloe Bennett',
    email: 'c.bennett@student.edupulse.edu',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    gradeLevel: 'Grade 11',
    branchId: 'br-2',
    branchName: 'North Innovation Wing',
    studentIdNumber: 'STU-2025-0104',
    parentContact: '+1 (555) 567-8901',
  },
];

export const INITIAL_CALENDAR_CONFIG: SchoolCalendarConfig = {
  totalWorkingDaysPerMonth: 22,
  perDayPenaltyRate: 150,
  holidays: [
    { date: '2026-09-01', name: 'Labor Day' },
    { date: '2026-10-12', name: 'Autumn Break' },
    { date: '2026-11-26', name: 'Thanksgiving Recess' },
  ],
};

export const INITIAL_STAFF_ATTENDANCE: StaffAttendanceRecord[] = [
  { id: 'satt-1', staffId: 'teacher-1', staffName: 'Prof. Elena Rostova', staffRole: 'teacher', branchId: 'br-1', branchName: 'Main Metropolitan Campus', date: '2026-08-07', checkInTime: '08:12 AM', status: 'present' },
  { id: 'satt-2', staffId: 'teacher-2', staffName: 'Dr. Robert Sterling', staffRole: 'teacher', branchId: 'br-1', branchName: 'Main Metropolitan Campus', date: '2026-08-07', checkInTime: '08:25 AM', status: 'present' },
  { id: 'satt-3', staffId: 'teacher-3', staffName: 'Ms. Maya Lin', staffRole: 'teacher', branchId: 'br-2', branchName: 'North Innovation Wing', date: '2026-08-07', checkInTime: '08:05 AM', status: 'present' },
  { id: 'satt-4', staffId: 'teacher-4', staffName: 'Mr. David Hayes', staffRole: 'teacher', branchId: 'br-2', branchName: 'North Innovation Wing', date: '2026-08-07', checkInTime: '08:45 AM', status: 'tardy', notes: 'Traffic delay' },
  { id: 'satt-5', staffId: 'staff-1', staffName: 'Rachel Adams', staffRole: 'staff', branchId: 'br-1', branchName: 'Main Metropolitan Campus', date: '2026-08-07', checkInTime: '08:00 AM', status: 'present' },
  
  // Historical entries for salary calculation
  { id: 'satt-6', staffId: 'teacher-1', staffName: 'Prof. Elena Rostova', staffRole: 'teacher', branchId: 'br-1', branchName: 'Main Metropolitan Campus', date: '2026-08-06', checkInTime: '08:10 AM', status: 'present' },
  { id: 'satt-7', staffId: 'teacher-1', staffName: 'Prof. Elena Rostova', staffRole: 'teacher', branchId: 'br-1', branchName: 'Main Metropolitan Campus', date: '2026-08-05', checkInTime: '08:15 AM', status: 'present' },
  { id: 'satt-8', staffId: 'teacher-1', staffName: 'Prof. Elena Rostova', staffRole: 'teacher', branchId: 'br-1', branchName: 'Main Metropolitan Campus', date: '2026-08-04', checkInTime: '—', status: 'absent', notes: 'Unexcused' },
  { id: 'satt-9', staffId: 'teacher-2', staffName: 'Dr. Robert Sterling', staffRole: 'teacher', branchId: 'br-1', branchName: 'Main Metropolitan Campus', date: '2026-08-06', checkInTime: '08:20 AM', status: 'present' },
];

export const INITIAL_ADMISSIONS: AdmissionApplication[] = [
  {
    id: 'adm-101',
    studentName: 'Julianna Davenport',
    dateOfBirth: '2009-04-12',
    gradeApplying: 'Grade 11',
    branchId: 'br-1',
    branchName: 'Main Metropolitan Campus',
    parentName: 'Harrison Davenport',
    parentPhone: '+1 (555) 987-6543',
    parentEmail: 'h.davenport@gmail.com',
    previousSchool: 'St. Jude International Academy',
    address: '742 Evergreen Terrace, Sector 4',
    notes: 'Honors STEM applicant with distinction in Physics.',
    status: 'pending',
    appliedAt: '2026-08-06',
  },
  {
    id: 'adm-102',
    studentName: 'Marcus Rodriguez Jr.',
    dateOfBirth: '2010-09-21',
    gradeApplying: 'Grade 9',
    branchId: 'br-2',
    branchName: 'North Innovation Wing',
    parentName: 'Elena Rodriguez',
    parentPhone: '+1 (555) 876-5432',
    parentEmail: 'elena.rodriguez@outlook.com',
    previousSchool: 'Westside Middle School',
    address: '128 Beacon Street, Apt 3B',
    notes: 'Keen interest in Computer Science and Robotics.',
    status: 'pending',
    appliedAt: '2026-08-07',
  },
];

export const INITIAL_TOPIC_PLANS: TeacherTopicPlan[] = [
  { id: 'tp-1', teacherId: 'teacher-1', courseId: 'course-1', courseName: 'AP Physics C: Mechanics', topicTitle: 'Rotational Torque & Angular Momentum Vectors', plannedDate: '2026-08-05', status: 'covered', notes: 'Covered with 3D vector diagrams' },
  { id: 'tp-2', teacherId: 'teacher-1', courseId: 'course-1', courseName: 'AP Physics C: Mechanics', topicTitle: 'Moment of Inertia for Non-Uniform Cylinders', plannedDate: '2026-08-07', status: 'covered', notes: 'Completed lab demo' },
  { id: 'tp-3', teacherId: 'teacher-1', courseId: 'course-1', courseName: 'AP Physics C: Mechanics', topicTitle: 'Simple Harmonic Motion & Torsional Pendulums', plannedDate: '2026-08-10', status: 'planned' },
  { id: 'tp-4', teacherId: 'teacher-1', courseId: 'course-2', courseName: 'Calculus BC & Linear Algebra', topicTitle: 'Taylor & Maclaurin Series Convergence Tests', plannedDate: '2026-08-06', status: 'covered' },
  { id: 'tp-5', teacherId: 'teacher-1', courseId: 'course-2', courseName: 'Calculus BC & Linear Algebra', topicTitle: 'Eigenvalues & Vector Matrix Transformations', plannedDate: '2026-08-08', status: 'delayed', notes: 'Postponed due to lab exercise' },
];

export const INITIAL_LEAVES: LeaveApplication[] = [
  {
    id: 'lv-1',
    applicantId: 'teacher-1',
    applicantName: 'Prof. Elena Rostova',
    applicantRole: 'teacher',
    branchId: 'br-1',
    startDate: '2026-08-15',
    endDate: '2026-08-16',
    leaveType: 'casual',
    reason: 'Attending Physics Education National Conference as keynote speaker.',
    status: 'approved',
    createdAt: '2026-08-02',
  },
  {
    id: 'lv-2',
    applicantId: 'teacher-2',
    applicantName: 'Dr. Robert Sterling',
    applicantRole: 'teacher',
    branchId: 'br-1',
    startDate: '2026-08-18',
    endDate: '2026-08-19',
    leaveType: 'sick',
    reason: 'Scheduled medical procedure and recovery.',
    status: 'pending',
    createdAt: '2026-08-06',
  },
];

export const INITIAL_ASSESSMENTS: AssessmentItem[] = [
  {
    id: 'asm-1',
    courseId: 'course-1',
    courseName: 'AP Physics C: Mechanics',
    title: 'Quiz 4: Rotational Mechanics & Torque',
    type: 'Quiz',
    dueDate: '2026-08-12',
    weightage: '10% of Final Grade',
    description: 'In-class quiz covering rotational kinematics and torque vectors.',
    scheduledDate: '2026-08-12',
    totalMarks: 50,
    syllabusTopics: ['Cross Products of Vectors', 'Torque Equations', 'Angular Acceleration', 'Rolling without slipping'],
  },
  {
    id: 'asm-2',
    courseId: 'course-2',
    courseName: 'Calculus BC & Linear Algebra',
    title: 'Unit Test 3: Infinite Series & Eigenvectors',
    type: 'Test',
    dueDate: '2026-08-15',
    weightage: '20% of Final Grade',
    description: 'Comprehensive test covering infinite series tests and matrix diagonalization.',
    scheduledDate: '2026-08-15',
    totalMarks: 100,
    syllabusTopics: ['Ratio and Root Tests', 'Power Series', 'Radius of Convergence', 'Matrix Diagonalization'],
  },
  {
    id: 'asm-3',
    courseId: 'course-3',
    courseName: 'Honors Organic Chemistry',
    title: 'Lab Exam: Spectroscopy & Reaction Kinetics',
    type: 'Exam',
    dueDate: '2026-08-19',
    weightage: '25% of Final Grade',
    description: 'Practical lab exam analyzing NMR and IR spectroscopy peaks.',
    scheduledDate: '2026-08-19',
    totalMarks: 100,
    syllabusTopics: ['NMR Spectroscopy', 'IR Absorption Peak Analysis', 'Reaction Rate Constants'],
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    code: 'PHYS-301',
    name: 'AP Physics C: Mechanics',
    department: 'Science & Mathematics',
    teacherId: 'teacher-1',
    teacherName: 'Prof. Elena Rostova',
    room: 'Room 204 (Lab A)',
    gradeLevel: 'Grade 11',
    color: 'emerald',
    branchId: 'br-1',
    enrolledStudentIds: ['student-1', 'student-2', 'student-3', 'student-4'],
  },
  {
    id: 'course-2',
    code: 'MATH-401',
    name: 'Calculus BC & Linear Algebra',
    department: 'Science & Mathematics',
    teacherId: 'teacher-1',
    teacherName: 'Prof. Elena Rostova',
    room: 'Room 204',
    gradeLevel: 'Grade 11',
    color: 'blue',
    branchId: 'br-1',
    enrolledStudentIds: ['student-1', 'student-2', 'student-3', 'student-4'],
  },
  {
    id: 'course-3',
    code: 'CHEM-201',
    name: 'Honors Organic Chemistry',
    department: 'Natural Sciences',
    teacherId: 'teacher-2',
    teacherName: 'Dr. Robert Sterling',
    room: 'Science Wing - Room 108',
    gradeLevel: 'Grade 11',
    color: 'purple',
    branchId: 'br-1',
    enrolledStudentIds: ['student-1', 'student-2', 'student-3'],
  },
  {
    id: 'course-4',
    code: 'HIST-102',
    name: 'AP World History: Modern',
    department: 'Humanities',
    teacherId: 'teacher-3',
    teacherName: 'Ms. Maya Lin',
    room: 'Humanities Hall - Room 312',
    gradeLevel: 'Grade 11',
    color: 'amber',
    branchId: 'br-2',
    enrolledStudentIds: ['student-1', 'student-2', 'student-3'],
  },
  {
    id: 'course-5',
    code: 'CS-101',
    name: 'Computer Science & AI Logic',
    department: 'Computer Science',
    teacherId: 'teacher-4',
    teacherName: 'Mr. David Hayes',
    room: 'Innovation Lab B',
    gradeLevel: 'Grade 11',
    color: 'indigo',
    branchId: 'br-2',
    enrolledStudentIds: ['student-1', 'student-3', 'student-4'],
  },
];

export const INITIAL_SCHEDULE: ScheduleItem[] = [
  // Monday
  { id: 'sch-1', courseId: 'course-1', courseCode: 'PHYS-301', courseName: 'AP Physics C', teacherName: 'Prof. Elena Rostova', room: 'Room 204', day: 'Monday', period: 1, startTime: '08:30 AM', endTime: '09:45 AM', color: 'emerald', branchId: 'br-1' },
  { id: 'sch-2', courseId: 'course-2', courseCode: 'MATH-401', courseName: 'Calculus BC', teacherName: 'Prof. Elena Rostova', room: 'Room 204', day: 'Monday', period: 2, startTime: '09:55 AM', endTime: '11:10 AM', color: 'blue', branchId: 'br-1' },
  { id: 'sch-3', courseId: 'course-3', courseCode: 'CHEM-201', courseName: 'Honors Organic Chemistry', teacherName: 'Dr. Robert Sterling', room: 'Room 108', day: 'Monday', period: 3, startTime: '11:20 AM', endTime: '12:35 PM', color: 'purple', branchId: 'br-1' },
  { id: 'sch-4', courseId: 'course-4', courseCode: 'HIST-102', courseName: 'AP World History', teacherName: 'Ms. Maya Lin', room: 'Room 312', day: 'Monday', period: 4, startTime: '01:25 PM', endTime: '02:40 PM', color: 'amber', branchId: 'br-2' },

  // Tuesday
  { id: 'sch-5', courseId: 'course-5', courseCode: 'CS-101', courseName: 'Computer Science Principles', teacherName: 'Mr. David Hayes', room: 'Lab B', day: 'Tuesday', period: 1, startTime: '08:30 AM', endTime: '09:45 AM', color: 'indigo', branchId: 'br-2' },
  { id: 'sch-7', courseId: 'course-1', courseCode: 'PHYS-301', courseName: 'AP Physics Lab', teacherName: 'Prof. Elena Rostova', room: 'Lab A', day: 'Tuesday', period: 3, startTime: '11:20 AM', endTime: '12:35 PM', color: 'emerald', branchId: 'br-1' },

  // Wednesday
  { id: 'sch-8', courseId: 'course-2', courseCode: 'MATH-401', courseName: 'Calculus BC', teacherName: 'Prof. Elena Rostova', room: 'Room 204', day: 'Wednesday', period: 1, startTime: '08:30 AM', endTime: '09:45 AM', color: 'blue', branchId: 'br-1' },
  { id: 'sch-9', courseId: 'course-3', courseCode: 'CHEM-201', courseName: 'Honors Organic Chemistry', teacherName: 'Dr. Robert Sterling', room: 'Room 108', day: 'Wednesday', period: 2, startTime: '09:55 AM', endTime: '11:10 AM', color: 'purple', branchId: 'br-1' },

  // Thursday
  { id: 'sch-11', courseId: 'course-1', courseCode: 'PHYS-301', courseName: 'AP Physics C', teacherName: 'Prof. Elena Rostova', room: 'Room 204', day: 'Thursday', period: 1, startTime: '08:30 AM', endTime: '09:45 AM', color: 'emerald', branchId: 'br-1' },
  { id: 'sch-12', courseId: 'course-4', courseCode: 'HIST-102', courseName: 'AP World History', teacherName: 'Ms. Maya Lin', room: 'Room 312', day: 'Thursday', period: 2, startTime: '09:55 AM', endTime: '11:10 AM', color: 'amber', branchId: 'br-2' },

  // Friday
  { id: 'sch-14', courseId: 'course-2', courseCode: 'MATH-401', courseName: 'Calculus BC Seminar', teacherName: 'Prof. Elena Rostova', room: 'Room 204', day: 'Friday', period: 1, startTime: '08:30 AM', endTime: '09:45 AM', color: 'blue', branchId: 'br-1' },
  { id: 'sch-15', courseId: 'course-5', courseCode: 'CS-101', courseName: 'Robotics Workshop', teacherName: 'Mr. David Hayes', room: 'Lab B', day: 'Friday', period: 2, startTime: '09:55 AM', endTime: '11:10 AM', color: 'indigo', branchId: 'br-2' },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att-1', studentId: 'student-1', studentName: 'Marcus Vance', courseId: 'course-1', courseName: 'AP Physics C', date: '2026-08-07', status: 'present' },
  { id: 'att-2', studentId: 'student-2', studentName: 'Sophia Rodriguez', courseId: 'course-1', courseName: 'AP Physics C', date: '2026-08-07', status: 'present' },
  { id: 'att-3', studentId: 'student-3', studentName: 'Ethan Thorne', courseId: 'course-1', courseName: 'AP Physics C', date: '2026-08-07', status: 'tardy', notes: 'Arrived 10 mins late' },
  { id: 'att-4', studentId: 'student-4', studentName: 'Chloe Bennett', courseId: 'course-1', courseName: 'AP Physics C', date: '2026-08-07', status: 'present' },
  { id: 'att-5', studentId: 'student-1', studentName: 'Marcus Vance', courseId: 'course-2', courseName: 'Calculus BC', date: '2026-08-06', status: 'present' },
];

export const INITIAL_GRADES: GradeRecord[] = [
  { id: 'grd-1', studentId: 'student-1', studentName: 'Marcus Vance', courseId: 'course-1', courseName: 'AP Physics C', title: 'Midterm Exam - Rotational Dynamics', category: 'Midterm', score: 94, maxScore: 100, date: '2026-07-28', feedback: 'Exceptional problem-solving skills on torque vectors.' },
  { id: 'grd-2', studentId: 'student-1', studentName: 'Marcus Vance', courseId: 'course-1', courseName: 'AP Physics C', title: 'Lab Report: Simple Harmonic Motion', category: 'Homework', score: 98, maxScore: 100, date: '2026-08-02', feedback: 'Thorough error margin analysis.' },
  { id: 'grd-3', studentId: 'student-1', studentName: 'Marcus Vance', courseId: 'course-2', courseName: 'Calculus BC', title: 'Quiz 3: Taylor Series', category: 'Quiz', score: 96, maxScore: 100, date: '2026-08-01' },
  { id: 'grd-4', studentId: 'student-1', studentName: 'Marcus Vance', courseId: 'course-3', courseName: 'Honors Chemistry', title: 'Chemical Kinetics Project', category: 'Project', score: 91, maxScore: 100, date: '2026-07-25' },
  { id: 'grd-5', studentId: 'student-1', studentName: 'Marcus Vance', courseId: 'course-5', courseName: 'Computer Science Principles', title: 'Python Neural Network Classifier', category: 'Project', score: 100, maxScore: 100, date: '2026-08-04', feedback: 'Masterful implementation!' },
  { id: 'grd-6', studentId: 'student-2', studentName: 'Sophia Rodriguez', courseId: 'course-1', courseName: 'AP Physics C', title: 'Midterm Exam - Rotational Dynamics', category: 'Midterm', score: 99, maxScore: 100, date: '2026-07-28', feedback: 'Top score in class!' },
  { id: 'grd-7', studentId: 'student-3', studentName: 'Ethan Thorne', courseId: 'course-1', courseName: 'AP Physics C', title: 'Midterm Exam - Rotational Dynamics', category: 'Midterm', score: 72, maxScore: 100, date: '2026-07-28' },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Mid-Term Examination Schedule Released for Fall Semester',
    content: 'All students and faculty please note that Mid-Term Examinations will take place from October 12th to October 16th. Room allocations and proctoring schedules are updated in the Course Scheduling portal.',
    authorName: 'Dr. Arthur Vance',
    authorRole: 'principal',
    date: '2026-08-06',
    priority: 'urgent',
    targetAudience: 'all',
  },
  {
    id: 'ann-2',
    title: 'Staff & Faculty Kiosk PIN Attendance System Online',
    content: 'All faculty and administrative staff can now check in via the branch Kiosk terminal using their 4-digit security PIN.',
    authorName: 'Dr. Sarah Jenkins',
    authorRole: 'admin',
    date: '2026-08-05',
    priority: 'normal',
    targetAudience: 'teachers',
  },
];
